> git push origin main:main
remote: error: GH013: Repository rule violations found for refs/heads/main.        
remote: 
remote: - GITHUB PUSH PROTECTION        
remote:   —————————————————————————————————————————        
remote:     Resolve the following violations before pushing again        
remote: 
remote:     - Push cannot contain secrets        
remote: 
remote:             
remote:      (?) Learn how to resolve a blocked push        
remote:      https://docs.github.com/code-security/secret-scanning/working-with-secret-scanning-and-push-protection/working-with-push-protection-from-the-command-line#resolving-a-blocked-push        
remote:             
remote:             
remote:       —— OpenAI API Key ————————————————————————————————————        
remote:        locations:        
remote:          - commit: 2f6d8c69b5c21124025457bd72edb6a016f33b71        
remote:            path: .env:21        
remote:          - commit: 11ffad9679b43e058d4e04ce165c22e87e041093        
remote:            path: .env:21        
remote:             
remote:        (?) To push, remove secret from commit(s) or follow this URL to allow the secret.        
remote:        https://github.com/Shreyojit/llm--powered-chatapp/security/secret-scanning/unblock-secret/2lTbhJKe7vqvRHML7Wj90H8mKqP        
remote:             
remote: 
remote: 
To https://github.com/Shreyojit/llm--powered-chatapp.git
 ! [remote rejected] main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/Shreyojit/llm--powered-chatapp.git'
